import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Founder & Full Stack Developer",
    company: "KembangIn Digital Nusantara",
    logo: "/images/careers/kembangin.png",
    location: "Lumajang, Indonesia",
    location_type: "Hybrid",
    type: "Part-time",
    start_date: "2024-03",
    end_date: null,
    industry: "Software House",
    link: "https://simak.kembang.in",
    responsibilities: [
      "Design and develop interactive websites and mobile applications based on client requirements.",
      "Collaborate with clients to understand project goals, gather feedback, and ensure the final product aligns with their vision.",
      "Create visually engaging user interfaces and optimize applications for a seamless user experience.",
      "Debug, test, and troubleshoot applications to ensure functionality, performance, and security.",
      "Continuously improve and update digital products to adapt to new technologies and user needs.",
    ],
    isShow: true,
  },

  {
    position: "Internship",
    company: "Institut Teknologi dan Sains Mandala",
    logo: "/images/careers/mandala.png",
    location: "Jember, Indonesia",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2024-09",
    end_date: null,
    industry: "University",
    link: "https://itsm.ac.id",
    responsibilities: [
      "Assist in the installation, configuration, and maintenance of campus IT systems, including hardware, software, and networking equipment.",
      "Provide technical support to students and staff, addressing IT-related inquiries and issues.",
      "Contribute to the development and enhancement of campus IT projects, including web development and system integration.",
      "Collaborate with IT team members to implement new technologies and improve campus systems and services.",
      "Create and maintain user documentation and training materials to help staff and students navigate IT resources.",
    ],
    isShow: true,
  },
  {
    position: "Full Stack Developer",
    company: "CV Sinergi Teknokarya",
    logo: "/images/careers/sinergi.png",
    location: "Jember, Indonesia",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2025-05",
    end_date: "2025-08",
    industry: "Software House",
    link: "https://sinergiteknokarya.com",
    responsibilities: [
      "Developing web applications and ensuring an optimal user experience.",
      "Writing clean, efficient, and maintainable code.",
      "Using version control systems (GitLab) to manage source code and team collaboration.",
      "Implementing DVCS (Development, Versioning, Configuration, and Source Control) to ensure structured development.",
      "Conducting testing and debugging to ensure the application runs smoothly.",
    ],
    isShow: true,
  },
  {
    position: "Discord Moderator",
    company: "Aico Community",
    logo: "/images/careers/aico.png",
    location: "Jakarta, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Part-time",
    start_date: "2024-08",
    end_date: "2025-09",
    industry: "Community",
    link: "https://instagram.com/aico.community",
    responsibilities: [
      "Moderate community interactions on Discord, ensuring a positive and safe environment for all members.",
      "Develop and maintain custom Discord bots to automate tasks, manage server activities, and enhance user engagement.",
      "Create and implement moderation tools to assist with user management, including banning, muting, and warning members as needed.",
      "Collaborate with the Aico Community team to organize events, announcements, and engage with members.",
      "Monitor community feedback, address concerns, and escalate issues to higher-level moderators when necessary.",
      "Assist in the integration of third-party bots and tools to enhance the server’s functionality.",
      "Write and maintain documentation for custom bots and moderation workflows to ensure easy access for team members.",
    ],
    isShow: true,
  },
  {
    position: "Full Stack Developer",
    company: "Fistechno Digital Solution",
    logo: "/images/careers/fistechno.png",
    location: "Jember, Indonesia 🇮🇩",
    location_type: "Remote",
    type: "Freelance",
    start_date: "2022-08",
    end_date: "2023-10",
    industry: "Software House",
    link: "https://www.linkedin.com/company/cv-mentari-teknologi-digital/",
    responsibilities: [
      "Develop and maintain both frontend and backend components of web applications, ensuring seamless user experience and functionality.",
      "Design and implement RESTful APIs for integration with frontend interfaces and third-party services.",
      "Write clean, efficient, and maintainable code following industry best practices.",
      "Troubleshoot and debug issues across the stack to ensure optimal application performance.",
      "Work with version control systems (such as Git) to manage codebase and collaborate effectively with the development team.",
      "Perform code reviews and provide constructive feedback to team members to improve code quality.",
      "Optimize web applications for maximum speed, scalability, and security.",
      "Stay up-to-date with the latest web development trends, tools, and technologies to enhance product features and performance.",
    ],
    isShow: true,
  },
  {
    position: "Internship",
    company: "PT. Mascitra Teknologi Informasi",
    logo: "/images/careers/mascitra.png",
    location: "Jember, Indonesia",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2022-03",
    end_date: "2022-06",
    industry: "IT Consultant",
    link: "https://mascitra.co.id",
    responsibilities: [
      "Developed both frontend and backend features for the Kepeg-Kemlu application, ensuring seamless integration and smooth user experience.",
      "Collaborated with the design and product teams to implement new features based on client requirements and user feedback.",
      "Built and maintained RESTful APIs to support frontend interactions with backend data and services.",
      "Implemented user authentication and authorization mechanisms to ensure secure access to sensitive data.",
      "Optimized application performance and scalability, ensuring the system could handle increasing traffic and data.",
      "Worked on the integration of third-party services and APIs to enhance functionality and improve the overall user experience.",
      "Participated in debugging and troubleshooting complex issues across the stack to improve application stability.",
      "Performed regular code reviews to ensure code quality and adherence to best practices.",
    ],
    isShow: true,
  }
];
